project_id = "mbymzyoxzpwmmpypnfol"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.heygen-direct]
verify_jwt = false

[functions.heygen-generate]
verify_jwt = false

# [functions.heygen-templates] - REMOVED: Now handled by backend
# verify_jwt = false

# [functions.heygen-template-detail] - REMOVED: Now handled by backend
# verify_jwt = false

[functions.heygen-webhook]
verify_jwt = false

[functions.openai-generate]
verify_jwt = false

[functions.openai-variable-suggestions]
verify_jwt = false

[functions.runwayml-generate]
verify_jwt = false

[functions.test-heygen]
verify_jwt = false