name: Full Stack CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend linting
        run: npm run lint

      - name: Build backend
        run: npm run build

      - name: Run backend tests (if available)
        run: npm test --if-present

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: backend-build
          path: backend/dist/
          retention-days: 7

  frontend-ci:
    runs-on: ubuntu-latest
    needs: backend-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend linting
        run: npm run lint

      - name: Type check frontend
        run: npx tsc --noEmit

      - name: Build frontend
        run: npm run build

      - name: Run frontend tests (if available)
        run: npm test --if-present

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: frontend-build
          path: dist/
          retention-days: 7

  integration-tests:
    runs-on: ubuntu-latest
    needs: [backend-ci, frontend-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/dist/

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: dist/

      - name: Run integration tests (if available)
        run: npm run test:integration --if-present

